[build]
  command = "npm run build"
  publish = "public/"

# Redirect rule defined in "_redirect" isn't working.
# using netlify.toml instead.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
